name: photo_editor_app
description: "A photo editor app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

  photo_manager: ^3.7.1
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  file_selector: ^0.9.0
  flutter_acrylic: ^1.1.4
  crop_your_image: ^2.0.0
  image: ^4.5.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  windows: true

flutter:
  uses-material-design: true
  generate: true
